# File: docker-compose.yml
version: '3.8'

services:
  # 1. Database
  postgres:
    image: postgres:16-alpine
    container_name: rental_db
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: rental_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - rental_network

  # 2. Backend API
  backend:
    build: ./backend
    container_name: rental_backend
    restart: always
    ports:
      - '3000:3000'
    environment:
      DATABASE_URL: "postgresql://myuser:mypassword@postgres:5432/rental_db?schema=public"
      JWT_SECRET: "7ea93db3dbc3d850ab939a30f7c1f9718669a757484931abb91fc634b517056fd81a63e06d70ae43bb4d3cb7207a9dd48f2a7d9df03555f2e39d651711200a1c" # ควรเปลี่ยนเป็นค่าที่ปลอดภัยใน Production
      LINE_CHANNEL_ACCESS_TOKEN: "zrYlBxHeQT9Dq5BRHQZn7SEjp12qS2RHwcBZPTuo+KZvFQUBa7sKX74zPlxRrqPHIR0HW4Q9mm9wZJAS6OIWqSyEbEX13Y96NdkgoODrUhnKNxyY8lBcCgSNhZ3rd1c0rkUxtNFaq07oFPVFAsCFWwdB04t89/1O/w1cDnyilFU="
      LINE_CHANNEL_SECRET: "0e2e163ef4db60123ea31ce9fd9301ec"
    depends_on:
      - postgres
    volumes:
      - ./backend/uploads:/app/uploads # Map โฟลเดอร์รูปภาพออกมาข้างนอก (กันหายเวลาลบ container)
    networks:
      - rental_network

  # 3. Frontend Admin (Back Office)
  frontend-admin:
    build: ./frontend-admin
    container_name: rental_admin
    restart: always
    ports:
      - '8080:80' # เข้าผ่าน http://IP_VPS:8080
    depends_on:
      - backend
    networks:
      - rental_network

  # 4. Frontend LIFF (Customer)
  frontend-liff:
    build: ./frontend-liff
    container_name: rental_liff
    restart: always
    ports:
      - '8081:80' # เข้าผ่าน http://IP_VPS:8081
    depends_on:
      - backend
    networks:
      - rental_network

  # (Optional) Adminer
  adminer:
    image: adminer
    restart: always
    ports:
      - 8090:8080 # เปลี่ยน port เลี่ยงชน frontend
    networks:
      - rental_network

  caddy:
    image: caddy:2
    container_name: rental_caddy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - backend
      - frontend-admin
      - frontend-liff
    networks:
      - rental_network

volumes:
  postgres_data:
  caddy_data:
  caddy_config:

networks:
  rental_network:
    driver: bridge

